
### POST request to server for Register
POST http://localhost:3000/auth/register
content-type: application/json

{
  "username": "Alma",
  "password": "Alma",
  "email": "AlmaMail"
}

###

### POST request to server for Login
POST http://localhost:3000/auth/login
content-type: application/json

{
  "username": "Alma",
  "password": "Alma"
}

###


### Get User Info
GET http://localhost:3000/auth/me
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNWI4YWIwYS03OTExLTRiOTctOTUyMi05MjRmZDg4NWUzNmMiLCJ1c2VybmFtZSI6IkFsbWEiLCJpYXQiOjE3NDUzMTE3NzUsImV4cCI6MTc0NTMxMjY3NX0.wqNsZehLQOF14z_-stVUrx2iSROKL_bbKKLwJFRifMY

###


### refresh token
POST http://localhost:3000/auth/refresh
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNWI4YWIwYS03OTExLTRiOTctOTUyMi05MjRmZDg4NWUzNmMiLCJ1c2VybmFtZSI6IkFsbWEiLCJpYXQiOjE3NDUzMTE3NDMsImV4cCI6MTc0NTMyMjU0M30.Z6uWx4o7pdXUJtEursLK6pj3sNkd5_7DxkSy6a1-bzM

###



### Logout
POST http://localhost:3000/auth/logout
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNWI4YWIwYS03OTExLTRiOTctOTUyMi05MjRmZDg4NWUzNmMiLCJ1c2VybmFtZSI6IkFsbWEiLCJpYXQiOjE3NDUwOTc0MTEsImV4cCI6MTc0NTEwMTAxMX0.y3wCXPIEVA9ljulO-DsCBuivsq1AhN1omjyMBDMqAQ0

###
