### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=WebStorm

### POST startQuit
POST localhost:3000/game/start
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNWI4YWIwYS03OTExLTRiOTctOTUyMi05MjRmZDg4NWUzNmMiLCJ1c2VybmFtZSI6IkFsbWEiLCJpYXQiOjE3NDc2NTk2NDYsImV4cCI6MTc0NzY2MDU0Nn0.Hzjz1AtTB4Rf1YM7vnTDoHZtvqg99fGaCphoBp99n64

{
  "quizId": "3183c364-c224-42f4-ac5b-196e24a8c142"
}


### POST answer
POST localhost:3000/game/question
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNWI4YWIwYS03OTExLTRiOTctOTUyMi05MjRmZDg4NWUzNmMiLCJ1c2VybmFtZSI6IkFsbWEiLCJpYXQiOjE3NDc2NTk2NDYsImV4cCI6MTc0NzY2MDU0Nn0.Hzjz1AtTB4Rf1YM7vnTDoHZtvqg99fGaCphoBp99n64

{
  "gameState": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJnYW1lIjp7InVzZXJJZCI6IjM1YjhhYjBhLTc5MTEtNGI5Ny05NTIyLTkyNGZkODg1ZTM2YyIsInF1aXpJZCI6IjMxODNjMzY0LWMyMjQtNDJmNC1hYzViLTE5NmUyNGE4YzE0MiIsImxpc3RPZlF1ZXN0aW9ucyI6W3siaWQiOiJkYjQ3ZGU1NS1hMWNlLTQ2OWQtOTBhMy1kZmM1ZjY3N2MyMjYiLCJ0cnlzIjozLCJzY29yZSI6MH0seyJpZCI6IjM2Yzk3ZDA5LTFkODAtNDJiNi05NDc4LTQ2ODY3MTM3YjJlYyIsInRyeXMiOjMsInNjb3JlIjowfSx7ImlkIjoiODhmNzY2NDAtZDNkMy00ZWM3LTg3ZDItZjNhYTljMmZjYTUzIiwidHJ5cyI6Mywic2NvcmUiOjB9XX0sImlhdCI6MTc0NzY1OTY3MiwiZXhwIjoxNzQ3NjY2ODcyfQ.RMecLoCTRIv6aDDRz-O1fpRU4vu89ErjIhcb8HcNSu8"
}


### POST check
POST localhost:3000/game/check
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNWI4YWIwYS03OTExLTRiOTctOTUyMi05MjRmZDg4NWUzNmMiLCJ1c2VybmFtZSI6IkFsbWEiLCJpYXQiOjE3NDc2NTk2NDYsImV4cCI6MTc0NzY2MDU0Nn0.Hzjz1AtTB4Rf1YM7vnTDoHZtvqg99fGaCphoBp99n64

{
 "gameState": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJnYW1lIjp7InVzZXJJZCI6IjM1YjhhYjBhLTc5MTEtNGI5Ny05NTIyLTkyNGZkODg1ZTM2YyIsInF1aXpJZCI6IjMxODNjMzY0LWMyMjQtNDJmNC1hYzViLTE5NmUyNGE4YzE0MiIsImxpc3RPZlF1ZXN0aW9ucyI6W3siaWQiOiJkYjQ3ZGU1NS1hMWNlLTQ2OWQtOTBhMy1kZmM1ZjY3N2MyMjYiLCJ0cnlzIjoxLCJzY29yZSI6Mn0seyJpZCI6IjM2Yzk3ZDA5LTFkODAtNDJiNi05NDc4LTQ2ODY3MTM3YjJlYyIsInRyeXMiOjMsInNjb3JlIjowfSx7ImlkIjoiODhmNzY2NDAtZDNkMy00ZWM3LTg3ZDItZjNhYTljMmZjYTUzIiwidHJ5cyI6Mywic2NvcmUiOjB9XX0sImlhdCI6MTc0NzY2MDAzNSwiZXhwIjoxNzQ3NjY3MjM1fQ.r7ULts28KbFho0yHDeY066e-Rb1vid_PhsyJJeWYstg",
  "questionId": "db47de55-a1ce-469d-90a3-dfc5f677c226",
  "answer": "Alma"
}
