### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=WebStorm

### POST startQuit
POST localhost:3000/game/start
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNWI4YWIwYS03OTExLTRiOTctOTUyMi05MjRmZDg4NWUzNmMiLCJ1c2VybmFtZSI6IkFsbWEiLCJpYXQiOjE3NDc2NTcyODIsImV4cCI6MTc0NzY1ODE4Mn0.sJXT7X9HmC0FEz_Ta1aKYchINm_v0s6a7zEiLBM9BfY

{
  "quizId": "3183c364-c224-42f4-ac5b-196e24a8c142"
}


### POST answer
POST localhost:3000/game/question
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNWI4YWIwYS03OTExLTRiOTctOTUyMi05MjRmZDg4NWUzNmMiLCJ1c2VybmFtZSI6IkFsbWEiLCJpYXQiOjE3NDc2NTcyODIsImV4cCI6MTc0NzY1ODE4Mn0.sJXT7X9HmC0FEz_Ta1aKYchINm_v0s6a7zEiLBM9BfY

{
  "gameState": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJnYW1lIjp7InVzZXJJZCI6IjM1YjhhYjBhLTc5MTEtNGI5Ny05NTIyLTkyNGZkODg1ZTM2YyIsInF1aXpJZCI6IjMxODNjMzY0LWMyMjQtNDJmNC1hYzViLTE5NmUyNGE4YzE0MiIsImxpc3RPZlF1ZXN0aW9ucyI6W3siaWQiOiJkYjQ3ZGU1NS1hMWNlLTQ2OWQtOTBhMy1kZmM1ZjY3N2MyMjYiLCJ0cnlzIjozLCJzY29yZSI6MH0seyJpZCI6IjM2Yzk3ZDA5LTFkODAtNDJiNi05NDc4LTQ2ODY3MTM3YjJlYyIsInRyeXMiOjMsInNjb3JlIjowfV19LCJpYXQiOjE3NDc2NTc2NDUsImV4cCI6MTc0NzY1ODU0NX0.CTACksZVQgutSEIF51unrWH0VUEI_2szspmb4Q9GOAE"
}


### POST check
POST localhost:3000/game/check
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNWI4YWIwYS03OTExLTRiOTctOTUyMi05MjRmZDg4NWUzNmMiLCJ1c2VybmFtZSI6IkFsbWEiLCJpYXQiOjE3NDc2NTkwNTUsImV4cCI6MTc0NzY1OTk1NX0.LOepONYTt6mxT3BRdutcogSTRBev27HIItJY0c1r9Dg

{
 "gameState": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJnYW1lIjp7InVzZXJJZCI6IjM1YjhhYjBhLTc5MTEtNGI5Ny05NTIyLTkyNGZkODg1ZTM2YyIsInF1aXpJZCI6IjMxODNjMzY0LWMyMjQtNDJmNC1hYzViLTE5NmUyNGE4YzE0MiIsImxpc3RPZlF1ZXN0aW9ucyI6W3siaWQiOiJkYjQ3ZGU1NS1hMWNlLTQ2OWQtOTBhMy1kZmM1ZjY3N2MyMjYiLCJ0cnlzIjozLCJzY29yZSI6MH0seyJpZCI6IjM2Yzk3ZDA5LTFkODAtNDJiNi05NDc4LTQ2ODY3MTM3YjJlYyIsInRyeXMiOjMsInNjb3JlIjowfV19LCJpYXQiOjE3NDc2NTc2NDUsImV4cCI6MTc0NzY1ODU0NX0.CTACksZVQgutSEIF51unrWH0VUEI_2szspmb4Q9GOAE",
  "questionId": "db47de55-a1ce-469d-90a3-dfc5f677c226",
  "answer": "Alma"
}
